-- 1. Create the table for sensor readings
create table public.sensor_readings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  device_id text,
  temperature numeric,
  raw_temperature numeric,
  humidity numeric,
  raw_humidity numeric,
  air_quality numeric,
  raw_air_quality numeric
);

-- 2. Enable Row Level Security (Security best practice)
alter table public.sensor_readings enable row level security;

-- 3. Create a Policy to allow the Dashboard (Anon Key) to INSERT data
create policy "Allow Public Insert" 
on public.sensor_readings 
for insert 
with check (true);

-- 4. Create a Policy to allow the Dashboard to READ data (for verification)
create policy "Allow Public Read" 
on public.sensor_readings 
for select 
using (true);
