-- COMPLETE SCHEMA FIX for EcoSync
-- Runs idempotently (safe to run multiple times)

-- 1. Ensure 'sensor_readings' table exists
CREATE TABLE IF NOT EXISTS public.sensor_readings (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    device_id text,
    temperature numeric,
    humidity numeric,
    pm25 numeric,
    user_id uuid
);

-- 2. Add ALL missed columns (Gas, Motion, Trust Score)
ALTER TABLE public.sensor_readings ADD COLUMN IF NOT EXISTS gas numeric;
ALTER TABLE public.sensor_readings ADD COLUMN IF NOT EXISTS raw_gas numeric;
ALTER TABLE public.sensor_readings ADD COLUMN IF NOT EXISTS motion numeric;
ALTER TABLE public.sensor_readings ADD COLUMN IF NOT EXISTS raw_motion numeric;
ALTER TABLE public.sensor_readings ADD COLUMN IF NOT EXISTS trust_score numeric; -- The missing one

-- 3. Grant permissions (Fixes RLS issues)
GRANT ALL ON TABLE public.sensor_readings TO anon;
GRANT ALL ON TABLE public.sensor_readings TO service_role;
GRANT ALL ON TABLE public.sensor_readings TO authenticated;

-- 4. Enable RLS but allow Anon inserts (for ESP32)
ALTER TABLE public.sensor_readings ENABLE ROW LEVEL SECURITY;

create policy "Enable insert for anon (ESP32)"
on public.sensor_readings for insert
with check (true);

create policy "Enable select for anon (Dashboard)"
on public.sensor_readings for select
using (true);

-- 5. Force Schema Cache Reload
NOTIFY pgrst, 'reload schema';

-- 6. Verification
SELECT column_name 
FROM information_schema.columns 
WHERE table_name = 'sensor_readings' 
AND column_name IN ('gas', 'motion', 'trust_score');
