
-- 1. Create the table if it doesn't exist
create table if not exists public.sensor_readings (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  device_id text,
  temperature numeric,
  raw_temperature numeric,
  humidity numeric,
  raw_humidity numeric,
  air_quality numeric,
  raw_air_quality numeric,
  wind_speed numeric,
  raw_wind_speed numeric
);

-- 2. Enable Row Level Security (RLS) - This is good practice
alter table public.sensor_readings enable row level security;

-- 3. Create a policy to allow ANYONE (anon) to INSERT data
-- Note: Requires dropping existing policy if it conflicts, or just run this:
drop policy if exists "Enable insert for anon" on public.sensor_readings;

create policy "Enable insert for anon"
on public.sensor_readings
for insert
to anon
with check (true);

-- 4. Create a policy to allow ANYONE to SELECT (READ) data
drop policy if exists "Enable select for anon" on public.sensor_readings;

create policy "Enable select for anon"
on public.sensor_readings
for select
to anon
using (true);
