import os
import subprocess
import sys
import platform

def run_command(command, cwd=None):
    print(f"[SETUP] Running: {command} in {cwd or '.'}")
    try:
        if platform.system() == "Windows":
            subprocess.check_call(command, shell=True, cwd=cwd)
        else:
            subprocess.check_call(command, shell=True, cwd=cwd, executable='/bin/bash')
    except subprocess.CalledProcessError as e:
        print(f"[ERROR] Command failed: {e}")
        sys.exit(1)

def setup_env_interactive(backend_dir):
    print("\n" + "="*50)
    print("   🔑 API CONFIGURATION WIZARD")
    print("   We need a few keys to power the AI & Weather features.")
    print("   (Press Enter to skip if you don't have one yet)")
    print("="*50 + "\n")

    env_path = os.path.join(backend_dir, '.env')
    
    # Read existing if present to show defaults
    existing = {}
    if os.path.exists(env_path):
        with open(env_path, 'r') as f:
            for line in f:
                if '=' in line and not line.startswith('#'):
                    k, v = line.strip().split('=', 1)
                    existing[k] = v

    # keys to prompt
    keys_to_ask = [
        ("OPENWEATHER_API_KEY", "OpenWeatherMap Key (for Weather Data)"),
        ("OPENAQ_API_KEY", "OpenAQ Key (Optional, for Air Quality)"),
        ("GEMINI_API_KEY", "Google Gemini Key (for AI Assistant)"),
        ("VITE_API_BASE_URL", "Backend URL (Default: http://localhost:8000)")
    ]

    new_env = {}
    
    for key, desc in keys_to_ask:
        default_val = existing.get(key, "")
        prompt_text = f"{desc} [{default_val}]: " if default_val else f"{desc}: "
        user_input = input(prompt_text).strip()
        
        if not user_input and default_val:
            new_env[key] = default_val
        elif user_input:
            new_env[key] = user_input
        else:
            # Set default for URL if empty
            if key == "VITE_API_BASE_URL":
                new_env[key] = "http://localhost:8000"
            else:
                new_env[key] = "" # Leave empty if skipped

    # Write .env
    print(f"\n[INFO] Saving configuration to {env_path}...")
    with open(env_path, 'w') as f:
        f.write(f"# Auto-generated by setup.py\n")
        f.write(f"ENVIRONMENT=development\n")
        for k, v in new_env.items():
            f.write(f"{k}={v}\n")
    print("[SUCCESS] API Keys saved!")

def main():
    print("="*50)
    print("   IoT Capstone Project - Interactive Setup 🚀")
    print("="*50)

    base_dir = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
    backend_dir = os.path.join(base_dir, 'backend')
    frontend_dir = os.path.join(base_dir, 'frontend')

    # 1. API Configuration
    setup_env_interactive(backend_dir)

    # 2. Backend Setup
    print("\n[STEP 2/3] Installing Backend Dependencies (Python)...")
    if not os.path.exists(backend_dir):
        print("Error: 'backend' directory not found.")
        return
    run_command(f"{sys.executable} -m pip install -r requirements.txt", cwd=backend_dir)

    # 3. Frontend Setup
    print("\n[STEP 3/3] Installing Frontend Dependencies (Node.js)...")
    if not os.path.exists(frontend_dir):
        print("Error: 'frontend' directory not found.")
        return

    try:
        run_command("npm install", cwd=frontend_dir)
    except:
        print("Warning: 'npm' not found. Please install Node.js.")

    print("\n" + "="*50)
    print("   ✅ SETUP COMPLETE!")
    print("   To launch the system, run:")
    print(f"   > python3 scripts/start.py")
    print("="*50)

if __name__ == "__main__":
    main()
